"""add created_at to cameras

Revision ID: e7b3a4a72200
Revises: 51a1c89ac215
Create Date: 2026-09-27 13:25:30.352675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b3a4a72200'
down_revision: Union[str, Sequence[str], None] = '51a1c89ac215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() ->None:
    """upgrade schema"""
    #2 give existing cameras a timestamp
    op.execute(
        "UPDATE cameras SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )
    #3 MAKE THE COLUMN REQUIRED
    with op.batch_alter_table("cameras") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            nullable=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'created_at')
    # ### end Alembic commands ###
